
name: build

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    
env:
  PROJECT_NAME: CleanArchitecture.Exceptions
    
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:    
      
    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./$PROJECT_NAME.sln
      
    - name: Build
      run: dotnet build ./$PROJECT_NAME.sln
      
    - name: Test
      run: dotnet test ./$PROJECT_NAME.sln
